### ISSUE TITLE
Changing the default starting date

### ISSUE THREAD

**Issue by vaibhav12aggarwal** [demarchisd/stacked-gantt#5] opened 2017-12-23 12:42 UTC
Hi 

We intend to change the initial starting date of the Gantt chart (the one that appears to the left of the Gantt chart when it loads at the start  (generally the currect date) to the start date of the first activity.

Please suggest.

Please find attached the snapshots for better understanding.

Regards,
Vaibhav

OnLoad:
![capture 1](https://user-images.githubusercontent.com/30471716/34319612-cb054232-e80c-11e7-8f26-b57498405ee8.PNG)

On selecting the start date of first activity:
![capture 2](https://user-images.githubusercontent.com/30471716/34319613-dc839e14-e80c-11e7-9ebf-85998fb778bf.PNG)

**Comment by demarchisd** [comment] 2017-12-28 10:27
Hello Vaibhav!

Actually, this should be done automatically.. Could you provide the data you're using to generate the image's chart?

**Comment by vaibhav12aggarwal** [comment] 2018-01-03 11:07
Hi Demarchisd
We are hereby attaching a code snippet for your refrence. 
First an empty gantt chart is called. 
And then a gantt chart with Activity data 
We are also attaching corresponding Pictures.

[gantt.txt](https://github.com/demarchisd/stacked-gantt/files/1600128/gantt.txt)

![gantt chart onload](https://user-images.githubusercontent.com/30471716/34518171-3a5aaa24-f0a4-11e7-979b-c4179c774f80.PNG)

![gantt chart with_activity_json](https://user-images.githubusercontent.com/30471716/34518184-50afe3c0-f0a4-11e7-83be-868ad27065df.PNG)

Thanks & Regards,
Vaibhav

**Comment by vaibhav12aggarwal** [comment] 2018-01-08 08:04
Do you have any updates for me?

Thanks & Regards,
Vaibhav

**Comment by demarchisd** [comment] 2018-01-08 10:32
Hello Vaibhav!

Could you please confirm that this is what you need:

1. The chart is initialized with no data, and the initial date is set to 03/01/2018;
2. You update the chart with some data, and the activities provided in this data begin in 05/01/2018;
3. Currently, when you update the chart, it draws the chart with the initial date as 05/01/2018 - but you need that the beginning of the chart remains as 03/01/2018, the same it was in step 1.

Is that correct? If so, could you explain why you need this padding of 2 days in the beginning? Maybe you could put one General Marker with date 03/01/2018 in your data - that way you'd force the chart to begin on this date.

Regards,

Bruno

**Comment by vaibhav12aggarwal** [comment] 2018-01-08 11:29
Hi Demarched

Thanks a lot for your responce.
Your understanding is fine but with a trivial change.
What we need is: 

1. The chart is initialized with no data, and the initial date is set to 03/01/2018 (Current date);
2. You update the chart with some data, and the activities provided in this data begin in 05/01/2018 (Starting date of the activity) ;
3. Currently, when we update the chart, it draws the chart with the initial date as 03/01/2018 (and NOT 05/01/2018) - but we need that the beginning of the chart moves to 05/01/2018, and NOT the same it was in step 1.

Right now when the chart is provided with the data (starting date as 05/01/2018), it does not scroll to make the initial date as 05/01/2018 and consequently the initail date remains as 03/01/2018 and the activity bar with the starting date as 05/01/2018 goes to the right of screen and not visible.

Regards,
Vaibhav.

**Comment by demarchisd** [comment] 2018-01-08 11:50
Well, that's an unexpected behavior, I'll have to make some further tests.

**Comment by demarchisd** [comment] 2018-01-08 15:45
Vaibhav,

I couldn't simulate the scenario you've described. In my tests, it works as you wanted it to. 

Please take a look at this fiddle: https://jsfiddle.net/cw14b2dn/

It initializes with a chart that has no activities (thus using the `defaultBeginDate` and `defaultEndDate` properties) and is populated with the actual data when the `Update Chart` button is clicked.

If you can't get your code working, I would suggest you to create a new fiddle simulating the problem, so I could investigate it.

Hope it helps!

Regards,

Bruno

**Comment by demarchisd** [comment] 2018-01-16 17:40
Hello Vaibhav,

Any updates about the problem?

**Comment by demarchisd** [comment] 2018-01-25 14:53
Closing the issue as it seems it's not a bug. If the problem persists, please open another ticket.

**Closed as completed by demarchisd** 2018-01-25 14:53 UTC
Labels: invalid
